.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -20,13 +20,22 @@ build:
 style:
   stage: style
   script:
-    - cp ../materials/linters/.clang-format .
     - clang-format --version # вывод версии clang-format для отладки
     - cd src/cat/
-    - clang-format -style=file -output-replacements-xml $(find . -name "*.c" -or -name "*.h") > format.xml || true
+    - clang-format -style=Google -output-replacements-xml $(find . -name "*.c" -or -name "*.h") > format.xml || true
     - cat format.xml # вывод результата clang-format для отображения в CI
     - |
-      if grep -q "<replacement " format.xml; then
+      if grep -q "offset" format.xml; then
+        echo "Code style check failed. Please run clang-format to fix formatting issues."
+        exit 1
+      else
+        echo "Code style check passed."
+      fi
+    - cd ../grep/
+        - clang-format -style=Google -output-replacements-xml $(find . -name "*.c" -or -name "*.h") > format.xml || true
+    - cat format.xml # вывод результата clang-format для отображения в CI
+    - |
+      if grep -q "offset" format.xml; then
         echo "Code style check failed. Please run clang-format to fix formatting issues."
         exit 1
       else
